### PR TITLE
 Update UI for momentum & hope

### LINKED ISSUE #14: Update UI for momentum & hope
Update ui for momentum and hope as it changes.

### PR DESCRIPTION
**Pull request by tannerwelsh**
Closes #14 

- [x] Momentum counter updates as you play cards
- [x] Home counter updates as you play cards

### CODE REVIEW

**Review by heckayla — CHANGES_REQUESTED** [review]
A few comments:

- Looks like the switch statement for updating momentum is backwards. Right now, it says (at Line 307 of `GameManager`):

switch (activePlayerCardCount)
                    {
                        case 0:
                            MomentumDisplay.Instance.SetMomentumFull();
                            break;
                        case 1:
                            MomentumDisplay.Instance.SetMomentumTwo();
                            break;
                        case 2:
                            MomentumDisplay.Instance.SetMomentumOne();
                            break;
                    }

This seems to be the reverse of what it should be; If there are zero active cards, then momentum should be empty, and if there is one active card, then momentum should be set to one, and so on. From my understanding, at least. This should be an easy fix though.

- Instead of setting `displayedImage` again in every function call for `MomentumDisplay` and `HopeDisplay`, you could set it once in a `Start()` function on each script so that it gets set when the game first starts, and never has to be set again. This would be significantly more efficient than repeated calls to `GetComponent()` and it would also make the code simpler.
- There is a cleaner way to do `SetMomentum` and `SetHope` than having separate functions for each value (it would involve using a single function that takes in an `enum` and evaluates it with a `switch` statement), but since the functions are so simple, I doubt it would help much to complicate things by having you change how those functions work.

Once you address those first two bullet points, this should be fine to merge. Good work!

**Comment by tannerwelsh** [comment]
Thanks @heckayla ! Great review. I'll work on integrating your feedback and ping you again when it's ready for re-review.

**Comment by tannerwelsh** [comment]
Since this PR has some conflicts with the other open PRs right now, I'm going to wait until those are merged and then redo the code here to match.

**Comment by heckayla** [comment]
Looks like those other PR's are merged in now, @tannerwelsh ! For the `CardTable` file, I would say just take the version on master, but the merging in `GameManager` will have to be more carefully managed.

**Review by heckayla — APPROVED** [review]
Looks good Tanner! Thanks for implementing the changes requested so well. Merge it!

**Pull request merged**
